"""Drives the engine through time and hands events to a sink.

* **realtime** — event time = now; transactions at a flat `transactions_per_second`, paced
  against a monotonic clock so a slow iteration is caught up instead of drifting.
* **backfill** — walks simulated minutes from `now - backfill_days` to now, drawing a
  Poisson number of transactions per store per minute from the demand curve; runs as fast as
  the sink accepts. Useful for warehouse history (trends, SCD2 over time).
"""

from __future__ import annotations

import math
import random
import time
from collections.abc import Callable, Iterable
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta
from typing import Protocol

from prometheus_client import CollectorRegistry, Counter

from retail_platform.config.settings import SimulatorSettings
from retail_platform.messaging.records import OutgoingEvent
from retail_platform.simulator.demand import expected_transactions_per_minute
from retail_platform.simulator.engine import RetailEngine
from retail_platform.simulator.faults import FaultInjector
from retail_platform.simulator.reference_data import Store


class EventSink(Protocol):
    def send(self, event: OutgoingEvent) -> None: ...

    def poll(self) -> None: ...


class StopSignal(Protocol):
    @property
    def requested(self) -> bool: ...


class SimulatorMetrics:
    def __init__(self, registry: CollectorRegistry) -> None:
        self.events_generated = Counter(
            "retail_simulator_events_generated_total",
            "Events generated by the simulator (before faults)",
            ["topic"],
            registry=registry,
        )
        self.faults_injected = Counter(
            "retail_simulator_faults_injected_total",
            "Fault-injected events",
            ["topic", "fault"],
            registry=registry,
        )


@dataclass
class RunStats:
    transactions: int = 0
    events_sent: int = 0
    bootstrap_events: int = 0


def poisson(rng: random.Random, lam: float) -> int:
    """Knuth's algorithm; fine for the small lambdas used per store-minute."""
    if lam <= 0:
        return 0
    limit, k, p = math.exp(-lam), 0, 1.0
    while True:
        p *= rng.random()
        if p <= limit:
            return k
        k += 1


class SimulationRunner:
    def __init__(
        self,
        *,
        engine: RetailEngine,
        faults: FaultInjector,
        sink: EventSink,
        settings: SimulatorSettings,
        rng: random.Random,
        stop: StopSignal,
        metrics: SimulatorMetrics | None = None,
        now: Callable[[], datetime] = lambda: datetime.now(UTC),
        monotonic: Callable[[], float] = time.monotonic,
        sleep: Callable[[float], None] = time.sleep,
    ) -> None:
        self._engine = engine
        self._faults = faults
        self._sink = sink
        self._settings = settings
        self._rng = rng
        self._stop = stop
        self._metrics = metrics
        self._now = now
        self._monotonic = monotonic
        self._sleep = sleep
        self.stats = RunStats()

    # ------------------------------------------------------------------ plumbing
    def _limit_reached(self) -> bool:
        limit = self._settings.max_events
        # The limit applies to generated traffic, not the one-off master-data bootstrap.
        return limit > 0 and self.stats.events_sent - self.stats.bootstrap_events >= limit

    def _emit(self, events: Iterable[OutgoingEvent], *, with_faults: bool = True) -> None:
        batch = list(events)
        if self._metrics:
            for e in batch:
                self._metrics.events_generated.labels(e.topic).inc()
        if with_faults:
            batch = self._faults.apply(batch)
        for event in batch:
            self._sink.send(event)
            self.stats.events_sent += 1
        self._sink.poll()

    def _maybe_master_data_change(self, at: datetime, per_transaction_hours: float) -> None:
        s = self._settings
        if self._rng.random() < s.product_change_rate_per_hour * per_transaction_hours:
            self._emit([self._engine.product_change(at)])
        if self._rng.random() < s.customer_change_rate_per_hour * per_transaction_hours:
            self._emit([self._engine.customer_change(at)])

    # ------------------------------------------------------------------ modes
    def run_realtime(self) -> RunStats:
        if self._settings.bootstrap_master_data:
            self._emit(self._engine.bootstrap(self._now()), with_faults=False)
            self.stats.bootstrap_events = self.stats.events_sent
        tps = self._settings.transactions_per_second
        interval = 1.0 / tps
        per_tx_hours = interval / 3600.0
        next_tick = self._monotonic()
        while not self._stop.requested and not self._limit_reached():
            now = self._now()
            self._emit(self._engine.due_deliveries(now))
            self._emit(self._engine.sale(now))
            self.stats.transactions += 1
            self._maybe_master_data_change(now, per_tx_hours)
            next_tick += interval
            delay = next_tick - self._monotonic()
            if delay > 0:
                self._sleep(delay)
            elif delay < -5.0:  # far behind (e.g. broker outage): don't burst to catch up
                next_tick = self._monotonic()
        return self.stats

    def run_backfill(self, stores: tuple[Store, ...]) -> RunStats:
        end = self._now().replace(second=0, microsecond=0)
        minute = end - timedelta(days=self._settings.backfill_days)
        if self._settings.bootstrap_master_data:
            self._emit(self._engine.bootstrap(minute), with_faults=False)
            self.stats.bootstrap_events = self.stats.events_sent
        per_day = self._settings.backfill_transactions_per_store_per_day
        while minute < end and not self._stop.requested and not self._limit_reached():
            for store in stores:
                lam = expected_transactions_per_minute(minute, store.timezone, per_day)
                lam *= store.traffic_weight
                for _ in range(poisson(self._rng, lam)):
                    at = minute + timedelta(seconds=self._rng.uniform(0, 59.999))
                    self._emit(self._engine.sale(at, store))
                    self.stats.transactions += 1
            self._emit(self._engine.due_deliveries(minute))
            self._maybe_master_data_change(minute, 1 / 60)
            minute += timedelta(minutes=1)
        return self.stats
