-- =============================================================================
-- STAGING -> dimensions (data-model.md §4 "SCD2 mechanics", ADR-006).
--
-- SCD2 strategy: "rebuild the affected keys".
--   1. Natural keys with new change events (from the staging stream) are "affected".
--   2. Their full version chain is recomputed from ALL staged changes, ordered by event time.
--      A new version starts only when a Type-2 attribute changes; Type-1 attributes take the
--      latest value on every version. The first version starts at 1900-01-01.
--   3. Existing rows for those keys (including inferred placeholders) are replaced.
--   4. Facts of those keys are re-pointed to the version valid at their event time.
-- Because surrogate keys are deterministic (ANALYTICS.SCD2_KEY), unchanged versions keep
-- their keys, out-of-order changes are handled correctly, and re-running is idempotent.
-- All four steps commit together or not at all.
-- =============================================================================

-- ----------------------------------------------------------------------------- DIM_STORE (SCD1)
CREATE OR REPLACE PROCEDURE {{DATABASE}}.ANALYTICS.SP_LOAD_DIM_STORE()
COPY GRANTS
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN
    -- 30 rows: a full-table MERGE is cheaper and simpler than a stream here.
    MERGE INTO {{DATABASE}}.ANALYTICS.DIM_STORE d
    USING {{DATABASE}}.STAGING.STG_STORES s
    ON d.STORE_ID = s.STORE_ID
    WHEN MATCHED AND (
           d.STORE_NAME   IS DISTINCT FROM s.STORE_NAME
        OR d.CITY         IS DISTINCT FROM s.CITY
        OR d.STATE        IS DISTINCT FROM s.STATE
        OR d.REGION       IS DISTINCT FROM s.REGION
        OR d.STORE_FORMAT IS DISTINCT FROM s.STORE_FORMAT
        OR d.SIZE_SQM     IS DISTINCT FROM s.SIZE_SQM
        OR d.OPENED_DATE  IS DISTINCT FROM s.OPENED_DATE
        OR d.TIMEZONE     IS DISTINCT FROM s.TIMEZONE)
    THEN UPDATE SET
        STORE_NAME = s.STORE_NAME, CITY = s.CITY, STATE = s.STATE, REGION = s.REGION,
        STORE_FORMAT = s.STORE_FORMAT, SIZE_SQM = s.SIZE_SQM, OPENED_DATE = s.OPENED_DATE,
        TIMEZONE = s.TIMEZONE, _UPDATED_AT = SYSDATE()
    WHEN NOT MATCHED THEN INSERT
        (STORE_KEY, STORE_ID, STORE_NAME, CITY, STATE, REGION, STORE_FORMAT, SIZE_SQM, OPENED_DATE, TIMEZONE)
    VALUES
        (MD5_NUMBER_LOWER64(s.STORE_ID), s.STORE_ID, s.STORE_NAME, s.CITY, s.STATE, s.REGION,
         s.STORE_FORMAT, s.SIZE_SQM, s.OPENED_DATE, s.TIMEZONE);
    RETURN 'dim_store merged: ' || SQLROWCOUNT;
END;
$$;

-- ----------------------------------------------------------------------------- DIM_PRODUCT (SCD2 + SCD1)
CREATE OR REPLACE PROCEDURE {{DATABASE}}.ANALYTICS.SP_LOAD_DIM_PRODUCT()
COPY GRANTS
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    versions INTEGER DEFAULT 0;
BEGIN
    BEGIN TRANSACTION;

    DELETE FROM {{DATABASE}}.STAGING.WRK_AFFECTED_KEYS WHERE ENTITY = 'PRODUCT';
    INSERT INTO {{DATABASE}}.STAGING.WRK_AFFECTED_KEYS (ENTITY, NATURAL_KEY)
        SELECT DISTINCT 'PRODUCT', PRODUCT_ID FROM {{DATABASE}}.STAGING.STG_PRODUCT_CHANGES_STREAM;

    DELETE FROM {{DATABASE}}.ANALYTICS.DIM_PRODUCT
    WHERE PRODUCT_ID IN (SELECT NATURAL_KEY FROM {{DATABASE}}.STAGING.WRK_AFFECTED_KEYS WHERE ENTITY = 'PRODUCT');

    INSERT INTO {{DATABASE}}.ANALYTICS.DIM_PRODUCT
        (PRODUCT_KEY, PRODUCT_ID, PRODUCT_NAME, UNIT_OF_MEASURE, BRAND, CATEGORY, SUBCATEGORY,
         LIST_PRICE, UNIT_COST, IS_ACTIVE, EFFECTIVE_FROM_UTC, EFFECTIVE_TO_UTC, IS_CURRENT,
         IS_INFERRED, VERSION_NUMBER, SOURCE_EVENT_ID)
    WITH changes AS (
        SELECT c.*,
               HASH(c.BRAND, c.CATEGORY, c.SUBCATEGORY, c.LIST_PRICE, c.UNIT_COST, c.IS_ACTIVE) AS T2_HASH,
               ROW_NUMBER() OVER (PARTITION BY c.PRODUCT_ID ORDER BY c.EVENT_TS_UTC, c.EVENT_ID) AS RN
        FROM {{DATABASE}}.STAGING.STG_PRODUCT_CHANGES c
        WHERE c.PRODUCT_ID IN (SELECT NATURAL_KEY FROM {{DATABASE}}.STAGING.WRK_AFFECTED_KEYS WHERE ENTITY = 'PRODUCT')
    ),
    version_starts AS (
        SELECT * FROM changes
        QUALIFY LAG(T2_HASH) OVER (PARTITION BY PRODUCT_ID ORDER BY RN) IS DISTINCT FROM T2_HASH
    ),
    latest_type1 AS (
        SELECT PRODUCT_ID, PRODUCT_NAME, UNIT_OF_MEASURE FROM changes
        QUALIFY ROW_NUMBER() OVER (PARTITION BY PRODUCT_ID ORDER BY RN DESC) = 1
    ),
    numbered AS (
        SELECT v.*,
               ROW_NUMBER() OVER (PARTITION BY v.PRODUCT_ID ORDER BY v.RN) AS VERSION_NUMBER
        FROM version_starts v
    ),
    effective AS (
        SELECT n.*,
               IFF(n.VERSION_NUMBER = 1, {{DATABASE}}.ANALYTICS.BEGINNING_OF_TIME(), n.EVENT_TS_UTC) AS EFFECTIVE_FROM
        FROM numbered n
    )
    SELECT
        {{DATABASE}}.ANALYTICS.SCD2_KEY(e.PRODUCT_ID, e.EFFECTIVE_FROM),
        e.PRODUCT_ID, t1.PRODUCT_NAME, t1.UNIT_OF_MEASURE, e.BRAND, e.CATEGORY, e.SUBCATEGORY,
        e.LIST_PRICE, e.UNIT_COST, e.IS_ACTIVE,
        e.EFFECTIVE_FROM,
        COALESCE(LEAD(e.EFFECTIVE_FROM) OVER (PARTITION BY e.PRODUCT_ID ORDER BY e.VERSION_NUMBER),
                 {{DATABASE}}.ANALYTICS.END_OF_TIME()),
        LEAD(e.EFFECTIVE_FROM) OVER (PARTITION BY e.PRODUCT_ID ORDER BY e.VERSION_NUMBER) IS NULL,
        FALSE,
        e.VERSION_NUMBER,
        e.EVENT_ID
    FROM effective e
    JOIN latest_type1 t1 ON t1.PRODUCT_ID = e.PRODUCT_ID;
    versions := SQLROWCOUNT;

    -- Re-point facts to the version valid at their event time (and refresh version-derived cost).
    UPDATE {{DATABASE}}.ANALYTICS.FACT_SALES f
    SET PRODUCT_KEY = d.PRODUCT_KEY,
        COST_AMOUNT = f.QUANTITY * d.UNIT_COST
    FROM {{DATABASE}}.ANALYTICS.DIM_PRODUCT d
    WHERE f.PRODUCT_ID = d.PRODUCT_ID
      AND d.PRODUCT_ID IN (SELECT NATURAL_KEY FROM {{DATABASE}}.STAGING.WRK_AFFECTED_KEYS WHERE ENTITY = 'PRODUCT')
      AND f.EVENT_TS_UTC >= d.EFFECTIVE_FROM_UTC AND f.EVENT_TS_UTC < d.EFFECTIVE_TO_UTC
      AND (f.PRODUCT_KEY <> d.PRODUCT_KEY OR f.COST_AMOUNT IS DISTINCT FROM f.QUANTITY * d.UNIT_COST);

    UPDATE {{DATABASE}}.ANALYTICS.FACT_INVENTORY f
    SET PRODUCT_KEY = d.PRODUCT_KEY,
        MOVEMENT_VALUE = f.QUANTITY_DELTA * COALESCE(f.UNIT_COST, d.UNIT_COST)
    FROM {{DATABASE}}.ANALYTICS.DIM_PRODUCT d
    WHERE f.PRODUCT_ID = d.PRODUCT_ID
      AND d.PRODUCT_ID IN (SELECT NATURAL_KEY FROM {{DATABASE}}.STAGING.WRK_AFFECTED_KEYS WHERE ENTITY = 'PRODUCT')
      AND f.EVENT_TS_UTC >= d.EFFECTIVE_FROM_UTC AND f.EVENT_TS_UTC < d.EFFECTIVE_TO_UTC
      AND (f.PRODUCT_KEY <> d.PRODUCT_KEY
           OR f.MOVEMENT_VALUE IS DISTINCT FROM f.QUANTITY_DELTA * COALESCE(f.UNIT_COST, d.UNIT_COST));

    COMMIT;
    RETURN 'dim_product versions rebuilt: ' || versions;
EXCEPTION
    WHEN OTHER THEN
        ROLLBACK;
        RAISE;
END;
$$;

-- ----------------------------------------------------------------------------- DIM_CUSTOMER (SCD2 + SCD1)
CREATE OR REPLACE PROCEDURE {{DATABASE}}.ANALYTICS.SP_LOAD_DIM_CUSTOMER()
COPY GRANTS
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    versions INTEGER DEFAULT 0;
BEGIN
    BEGIN TRANSACTION;

    DELETE FROM {{DATABASE}}.STAGING.WRK_AFFECTED_KEYS WHERE ENTITY = 'CUSTOMER';
    INSERT INTO {{DATABASE}}.STAGING.WRK_AFFECTED_KEYS (ENTITY, NATURAL_KEY)
        SELECT DISTINCT 'CUSTOMER', CUSTOMER_ID FROM {{DATABASE}}.STAGING.STG_CUSTOMER_CHANGES_STREAM;

    DELETE FROM {{DATABASE}}.ANALYTICS.DIM_CUSTOMER
    WHERE CUSTOMER_ID IN (SELECT NATURAL_KEY FROM {{DATABASE}}.STAGING.WRK_AFFECTED_KEYS WHERE ENTITY = 'CUSTOMER');

    INSERT INTO {{DATABASE}}.ANALYTICS.DIM_CUSTOMER
        (CUSTOMER_KEY, CUSTOMER_ID, LOYALTY_TIER, HOME_STORE_ID, CITY, STATE, SIGNUP_DATE, AGE_BAND,
         MARKETING_OPT_IN, HAS_EMAIL, EFFECTIVE_FROM_UTC, EFFECTIVE_TO_UTC, IS_CURRENT, IS_INFERRED,
         VERSION_NUMBER, SOURCE_EVENT_ID)
    WITH changes AS (
        SELECT c.*,
               HASH(c.LOYALTY_TIER, c.HOME_STORE_ID, c.CITY, c.STATE) AS T2_HASH,
               ROW_NUMBER() OVER (PARTITION BY c.CUSTOMER_ID ORDER BY c.EVENT_TS_UTC, c.EVENT_ID) AS RN
        FROM {{DATABASE}}.STAGING.STG_CUSTOMER_CHANGES c
        WHERE c.CUSTOMER_ID IN (SELECT NATURAL_KEY FROM {{DATABASE}}.STAGING.WRK_AFFECTED_KEYS WHERE ENTITY = 'CUSTOMER')
    ),
    version_starts AS (
        SELECT * FROM changes
        QUALIFY LAG(T2_HASH) OVER (PARTITION BY CUSTOMER_ID ORDER BY RN) IS DISTINCT FROM T2_HASH
    ),
    latest_type1 AS (
        SELECT CUSTOMER_ID, SIGNUP_DATE, BIRTH_YEAR, MARKETING_OPT_IN, EMAIL_SHA256 FROM changes
        QUALIFY ROW_NUMBER() OVER (PARTITION BY CUSTOMER_ID ORDER BY RN DESC) = 1
    ),
    numbered AS (
        SELECT v.*, ROW_NUMBER() OVER (PARTITION BY v.CUSTOMER_ID ORDER BY v.RN) AS VERSION_NUMBER
        FROM version_starts v
    ),
    effective AS (
        SELECT n.*,
               IFF(n.VERSION_NUMBER = 1, {{DATABASE}}.ANALYTICS.BEGINNING_OF_TIME(), n.EVENT_TS_UTC) AS EFFECTIVE_FROM
        FROM numbered n
    )
    SELECT
        {{DATABASE}}.ANALYTICS.SCD2_KEY(e.CUSTOMER_ID, e.EFFECTIVE_FROM),
        e.CUSTOMER_ID, e.LOYALTY_TIER, e.HOME_STORE_ID, e.CITY, e.STATE,
        t1.SIGNUP_DATE,
        CASE
            WHEN t1.BIRTH_YEAR IS NULL THEN 'Unknown'
            WHEN YEAR(CURRENT_DATE()) - t1.BIRTH_YEAR < 25 THEN '18-24'
            WHEN YEAR(CURRENT_DATE()) - t1.BIRTH_YEAR < 35 THEN '25-34'
            WHEN YEAR(CURRENT_DATE()) - t1.BIRTH_YEAR < 45 THEN '35-44'
            WHEN YEAR(CURRENT_DATE()) - t1.BIRTH_YEAR < 55 THEN '45-54'
            WHEN YEAR(CURRENT_DATE()) - t1.BIRTH_YEAR < 65 THEN '55-64'
            ELSE '65+'
        END,
        t1.MARKETING_OPT_IN,
        t1.EMAIL_SHA256 IS NOT NULL,
        e.EFFECTIVE_FROM,
        COALESCE(LEAD(e.EFFECTIVE_FROM) OVER (PARTITION BY e.CUSTOMER_ID ORDER BY e.VERSION_NUMBER),
                 {{DATABASE}}.ANALYTICS.END_OF_TIME()),
        LEAD(e.EFFECTIVE_FROM) OVER (PARTITION BY e.CUSTOMER_ID ORDER BY e.VERSION_NUMBER) IS NULL,
        FALSE,
        e.VERSION_NUMBER,
        e.EVENT_ID
    FROM effective e
    JOIN latest_type1 t1 ON t1.CUSTOMER_ID = e.CUSTOMER_ID;
    versions := SQLROWCOUNT;

    UPDATE {{DATABASE}}.ANALYTICS.FACT_SALES f
    SET CUSTOMER_KEY = d.CUSTOMER_KEY
    FROM {{DATABASE}}.ANALYTICS.DIM_CUSTOMER d
    WHERE f.CUSTOMER_ID = d.CUSTOMER_ID
      AND d.CUSTOMER_ID IN (SELECT NATURAL_KEY FROM {{DATABASE}}.STAGING.WRK_AFFECTED_KEYS WHERE ENTITY = 'CUSTOMER')
      AND f.EVENT_TS_UTC >= d.EFFECTIVE_FROM_UTC AND f.EVENT_TS_UTC < d.EFFECTIVE_TO_UTC
      AND f.CUSTOMER_KEY <> d.CUSTOMER_KEY;

    COMMIT;
    RETURN 'dim_customer versions rebuilt: ' || versions;
EXCEPTION
    WHEN OTHER THEN
        ROLLBACK;
        RAISE;
END;
$$;

CREATE OR REPLACE PROCEDURE {{DATABASE}}.ANALYTICS.SP_LOAD_DIMENSIONS()
COPY GRANTS
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN
    CALL {{DATABASE}}.ANALYTICS.SP_LOAD_DIM_STORE();
    CALL {{DATABASE}}.ANALYTICS.SP_LOAD_DIM_PRODUCT();
    CALL {{DATABASE}}.ANALYTICS.SP_LOAD_DIM_CUSTOMER();
    RETURN 'dimensions loaded';
END;
$$;
