-- =============================================================================
-- STAGING -> facts (data-model.md §4).
--
-- 1. Late-arriving dimensions: any product/customer referenced by new fact rows but absent
--    from its dimension gets an INFERRED member (first-version key, 'Unknown' attributes).
-- 2. MERGE on the deterministic fact key: re-running never duplicates (ADR-007).
-- 3. Point-in-time lookup: the dimension version whose [from, to) interval contains the
--    event time - "category as it was when sold".
-- =============================================================================

CREATE OR REPLACE PROCEDURE {{DATABASE}}.ANALYTICS.SP_LOAD_FACT_SALES()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    loaded INTEGER DEFAULT 0;
BEGIN
    BEGIN TRANSACTION;

    INSERT INTO {{DATABASE}}.ANALYTICS.DIM_PRODUCT
        (PRODUCT_KEY, PRODUCT_ID, PRODUCT_NAME, BRAND, CATEGORY, SUBCATEGORY, EFFECTIVE_FROM_UTC,
         EFFECTIVE_TO_UTC, IS_CURRENT, IS_INFERRED, VERSION_NUMBER)
    SELECT {{DATABASE}}.ANALYTICS.SCD2_KEY(s.PRODUCT_ID, {{DATABASE}}.ANALYTICS.BEGINNING_OF_TIME()),
           s.PRODUCT_ID, 'Unknown (inferred)', 'Unknown', 'Unknown', 'Unknown',
           {{DATABASE}}.ANALYTICS.BEGINNING_OF_TIME(), {{DATABASE}}.ANALYTICS.END_OF_TIME(), TRUE, TRUE, 1
    FROM (SELECT DISTINCT PRODUCT_ID FROM {{DATABASE}}.STAGING.STG_POS_TRANSACTION_LINES_STREAM) s
    WHERE NOT EXISTS (SELECT 1 FROM {{DATABASE}}.ANALYTICS.DIM_PRODUCT d WHERE d.PRODUCT_ID = s.PRODUCT_ID);

    INSERT INTO {{DATABASE}}.ANALYTICS.DIM_CUSTOMER
        (CUSTOMER_KEY, CUSTOMER_ID, LOYALTY_TIER, EFFECTIVE_FROM_UTC, EFFECTIVE_TO_UTC, IS_CURRENT,
         IS_INFERRED, VERSION_NUMBER)
    SELECT {{DATABASE}}.ANALYTICS.SCD2_KEY(s.CUSTOMER_ID, {{DATABASE}}.ANALYTICS.BEGINNING_OF_TIME()),
           s.CUSTOMER_ID, 'Unknown (inferred)',
           {{DATABASE}}.ANALYTICS.BEGINNING_OF_TIME(), {{DATABASE}}.ANALYTICS.END_OF_TIME(), TRUE, TRUE, 1
    FROM (SELECT DISTINCT CUSTOMER_ID FROM {{DATABASE}}.STAGING.STG_POS_TRANSACTION_LINES_STREAM
          WHERE CUSTOMER_ID IS NOT NULL) s
    WHERE NOT EXISTS (SELECT 1 FROM {{DATABASE}}.ANALYTICS.DIM_CUSTOMER d WHERE d.CUSTOMER_ID = s.CUSTOMER_ID);

    MERGE INTO {{DATABASE}}.ANALYTICS.FACT_SALES f
    USING (
        SELECT
            MD5_NUMBER_LOWER64(l.TRANSACTION_ID || '|' || l.LINE_NUMBER)            AS SALES_LINE_KEY,
            COALESCE(dd.DATE_KEY, -1)                                                AS DATE_KEY,
            COALESCE(st.STORE_KEY, -1)                                               AS STORE_KEY,
            COALESCE(p.PRODUCT_KEY, -1)                                              AS PRODUCT_KEY,
            IFF(l.CUSTOMER_ID IS NULL, -2, COALESCE(c.CUSTOMER_KEY, -1))             AS CUSTOMER_KEY,
            l.TRANSACTION_ID, l.LINE_NUMBER, l.PAYMENT_METHOD, l.REGISTER_ID,
            l.STORE_ID, l.PRODUCT_ID, l.CUSTOMER_ID,
            l.EVENT_TS_UTC, l.EVENT_TS_LOCAL, l.LOCAL_HOUR,
            l.QUANTITY, l.UNIT_PRICE, l.GROSS_AMOUNT, l.DISCOUNT_AMOUNT, l.NET_AMOUNT,
            l.QUANTITY * p.UNIT_COST                                                 AS COST_AMOUNT,
            l.EVENT_ID
        FROM {{DATABASE}}.STAGING.STG_POS_TRANSACTION_LINES_STREAM l
        LEFT JOIN {{DATABASE}}.ANALYTICS.DIM_DATE dd ON dd.FULL_DATE = l.BUSINESS_DATE
        LEFT JOIN {{DATABASE}}.ANALYTICS.DIM_STORE st ON st.STORE_ID = l.STORE_ID
        LEFT JOIN {{DATABASE}}.ANALYTICS.DIM_PRODUCT p
               ON p.PRODUCT_ID = l.PRODUCT_ID
              AND l.EVENT_TS_UTC >= p.EFFECTIVE_FROM_UTC AND l.EVENT_TS_UTC < p.EFFECTIVE_TO_UTC
        LEFT JOIN {{DATABASE}}.ANALYTICS.DIM_CUSTOMER c
               ON c.CUSTOMER_ID = l.CUSTOMER_ID
              AND l.EVENT_TS_UTC >= c.EFFECTIVE_FROM_UTC AND l.EVENT_TS_UTC < c.EFFECTIVE_TO_UTC
    ) s
    ON f.SALES_LINE_KEY = s.SALES_LINE_KEY
    WHEN NOT MATCHED THEN INSERT
        (SALES_LINE_KEY, DATE_KEY, STORE_KEY, PRODUCT_KEY, CUSTOMER_KEY, TRANSACTION_ID, LINE_NUMBER,
         PAYMENT_METHOD, REGISTER_ID, STORE_ID, PRODUCT_ID, CUSTOMER_ID, EVENT_TS_UTC, EVENT_TS_LOCAL,
         LOCAL_HOUR, QUANTITY, UNIT_PRICE, GROSS_AMOUNT, DISCOUNT_AMOUNT, NET_AMOUNT, COST_AMOUNT, EVENT_ID)
    VALUES
        (s.SALES_LINE_KEY, s.DATE_KEY, s.STORE_KEY, s.PRODUCT_KEY, s.CUSTOMER_KEY, s.TRANSACTION_ID,
         s.LINE_NUMBER, s.PAYMENT_METHOD, s.REGISTER_ID, s.STORE_ID, s.PRODUCT_ID, s.CUSTOMER_ID,
         s.EVENT_TS_UTC, s.EVENT_TS_LOCAL, s.LOCAL_HOUR, s.QUANTITY, s.UNIT_PRICE, s.GROSS_AMOUNT,
         s.DISCOUNT_AMOUNT, s.NET_AMOUNT, s.COST_AMOUNT, s.EVENT_ID);
    loaded := SQLROWCOUNT;

    COMMIT;
    RETURN 'fact_sales rows loaded: ' || loaded;
EXCEPTION
    WHEN OTHER THEN
        ROLLBACK;
        RAISE;
END;
$$;

CREATE OR REPLACE PROCEDURE {{DATABASE}}.ANALYTICS.SP_LOAD_FACT_INVENTORY()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    loaded INTEGER DEFAULT 0;
BEGIN
    BEGIN TRANSACTION;

    INSERT INTO {{DATABASE}}.ANALYTICS.DIM_PRODUCT
        (PRODUCT_KEY, PRODUCT_ID, PRODUCT_NAME, BRAND, CATEGORY, SUBCATEGORY, EFFECTIVE_FROM_UTC,
         EFFECTIVE_TO_UTC, IS_CURRENT, IS_INFERRED, VERSION_NUMBER)
    SELECT {{DATABASE}}.ANALYTICS.SCD2_KEY(s.PRODUCT_ID, {{DATABASE}}.ANALYTICS.BEGINNING_OF_TIME()),
           s.PRODUCT_ID, 'Unknown (inferred)', 'Unknown', 'Unknown', 'Unknown',
           {{DATABASE}}.ANALYTICS.BEGINNING_OF_TIME(), {{DATABASE}}.ANALYTICS.END_OF_TIME(), TRUE, TRUE, 1
    FROM (SELECT DISTINCT PRODUCT_ID FROM {{DATABASE}}.STAGING.STG_INVENTORY_MOVEMENTS_STREAM) s
    WHERE NOT EXISTS (SELECT 1 FROM {{DATABASE}}.ANALYTICS.DIM_PRODUCT d WHERE d.PRODUCT_ID = s.PRODUCT_ID);

    MERGE INTO {{DATABASE}}.ANALYTICS.FACT_INVENTORY f
    USING (
        SELECT
            MD5_NUMBER_LOWER64(m.MOVEMENT_ID)                AS INVENTORY_MOVEMENT_KEY,
            COALESCE(dd.DATE_KEY, -1)                        AS DATE_KEY,
            COALESCE(st.STORE_KEY, -1)                       AS STORE_KEY,
            COALESCE(p.PRODUCT_KEY, -1)                      AS PRODUCT_KEY,
            m.MOVEMENT_ID, m.MOVEMENT_TYPE, m.REASON_CODE, m.REFERENCE_ID, m.STORE_ID, m.PRODUCT_ID,
            m.EVENT_TS_UTC, m.EVENT_TS_LOCAL, m.QUANTITY_DELTA, m.QUANTITY_ON_HAND_AFTER,
            m.UNIT_COST,
            m.QUANTITY_DELTA * COALESCE(m.UNIT_COST, p.UNIT_COST) AS MOVEMENT_VALUE,
            m.EVENT_ID
        FROM {{DATABASE}}.STAGING.STG_INVENTORY_MOVEMENTS_STREAM m
        LEFT JOIN {{DATABASE}}.ANALYTICS.DIM_DATE dd ON dd.FULL_DATE = m.BUSINESS_DATE
        LEFT JOIN {{DATABASE}}.ANALYTICS.DIM_STORE st ON st.STORE_ID = m.STORE_ID
        LEFT JOIN {{DATABASE}}.ANALYTICS.DIM_PRODUCT p
               ON p.PRODUCT_ID = m.PRODUCT_ID
              AND m.EVENT_TS_UTC >= p.EFFECTIVE_FROM_UTC AND m.EVENT_TS_UTC < p.EFFECTIVE_TO_UTC
    ) s
    ON f.INVENTORY_MOVEMENT_KEY = s.INVENTORY_MOVEMENT_KEY
    WHEN NOT MATCHED THEN INSERT
        (INVENTORY_MOVEMENT_KEY, DATE_KEY, STORE_KEY, PRODUCT_KEY, MOVEMENT_ID, MOVEMENT_TYPE,
         REASON_CODE, REFERENCE_ID, STORE_ID, PRODUCT_ID, EVENT_TS_UTC, EVENT_TS_LOCAL,
         QUANTITY_DELTA, QUANTITY_ON_HAND_AFTER, UNIT_COST, MOVEMENT_VALUE, EVENT_ID)
    VALUES
        (s.INVENTORY_MOVEMENT_KEY, s.DATE_KEY, s.STORE_KEY, s.PRODUCT_KEY, s.MOVEMENT_ID,
         s.MOVEMENT_TYPE, s.REASON_CODE, s.REFERENCE_ID, s.STORE_ID, s.PRODUCT_ID, s.EVENT_TS_UTC,
         s.EVENT_TS_LOCAL, s.QUANTITY_DELTA, s.QUANTITY_ON_HAND_AFTER, s.UNIT_COST,
         s.MOVEMENT_VALUE, s.EVENT_ID);
    loaded := SQLROWCOUNT;

    COMMIT;
    RETURN 'fact_inventory rows loaded: ' || loaded;
EXCEPTION
    WHEN OTHER THEN
        ROLLBACK;
        RAISE;
END;
$$;

CREATE OR REPLACE PROCEDURE {{DATABASE}}.ANALYTICS.SP_LOAD_FACTS()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN
    CALL {{DATABASE}}.ANALYTICS.SP_LOAD_FACT_SALES();
    CALL {{DATABASE}}.ANALYTICS.SP_LOAD_FACT_INVENTORY();
    RETURN 'facts loaded';
END;
$$;

-- ----------------------------------------------------------------------------- periodic snapshot
-- Grain: store x product x business date. Idempotent for a date (delete + insert in one txn).
-- P_DATE NULL = yesterday in Malaysian local time (the daily task's default).
CREATE OR REPLACE PROCEDURE {{DATABASE}}.ANALYTICS.SP_BUILD_INVENTORY_SNAPSHOT(P_DATE DATE)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    d DATE;
    dk NUMBER(8,0);
    end_of_day_utc TIMESTAMP_NTZ;
    rows_written INTEGER DEFAULT 0;
BEGIN
    d := COALESCE(P_DATE, DATEADD(DAY, -1, TO_DATE(CONVERT_TIMEZONE('Asia/Kuala_Lumpur', CURRENT_TIMESTAMP()))));
    dk := {{DATABASE}}.ANALYTICS.DATE_KEY(d);
    end_of_day_utc := CONVERT_TIMEZONE('Asia/Kuala_Lumpur', 'UTC', DATEADD(DAY, 1, d)::TIMESTAMP_NTZ);

    BEGIN TRANSACTION;
    DELETE FROM {{DATABASE}}.ANALYTICS.FACT_INVENTORY_SNAPSHOT WHERE DATE_KEY = :dk;

    INSERT INTO {{DATABASE}}.ANALYTICS.FACT_INVENTORY_SNAPSHOT
        (DATE_KEY, STORE_KEY, PRODUCT_KEY, STORE_ID, PRODUCT_ID, CLOSING_ON_HAND, CLOSING_VALUE,
         UNITS_RECEIVED, UNITS_SOLD, UNITS_ADJUSTED, AVG_DAILY_UNITS_SOLD_7D, IS_BELOW_REORDER_POINT)
    WITH history AS (
        SELECT * FROM {{DATABASE}}.ANALYTICS.FACT_INVENTORY
        WHERE TO_DATE(EVENT_TS_LOCAL) <= :d
    ),
    closing AS (
        -- Latest source-reported level on or before the day (carries forward quiet days).
        SELECT STORE_ID, PRODUCT_ID, QUANTITY_ON_HAND_AFTER AS CLOSING_ON_HAND
        FROM history
        QUALIFY ROW_NUMBER() OVER (PARTITION BY STORE_ID, PRODUCT_ID
                                   ORDER BY EVENT_TS_UTC DESC, MOVEMENT_ID DESC) = 1
    ),
    today AS (
        SELECT STORE_ID, PRODUCT_ID,
               SUM(IFF(MOVEMENT_TYPE = 'RECEIPT', QUANTITY_DELTA, 0))     AS UNITS_RECEIVED,
               SUM(IFF(MOVEMENT_TYPE = 'SALE', -QUANTITY_DELTA, 0))       AS UNITS_SOLD,
               SUM(IFF(MOVEMENT_TYPE = 'ADJUSTMENT', QUANTITY_DELTA, 0))  AS UNITS_ADJUSTED
        FROM history
        WHERE TO_DATE(EVENT_TS_LOCAL) = :d
        GROUP BY STORE_ID, PRODUCT_ID
    ),
    last_7_days AS (
        SELECT STORE_ID, PRODUCT_ID,
               SUM(IFF(MOVEMENT_TYPE = 'SALE', -QUANTITY_DELTA, 0)) / 7.0 AS AVG_DAILY_UNITS_SOLD
        FROM history
        WHERE TO_DATE(EVENT_TS_LOCAL) > DATEADD(DAY, -7, :d)
        GROUP BY STORE_ID, PRODUCT_ID
    )
    SELECT
        :dk,
        COALESCE(st.STORE_KEY, -1),
        COALESCE(p.PRODUCT_KEY, -1),
        c.STORE_ID,
        c.PRODUCT_ID,
        c.CLOSING_ON_HAND,
        c.CLOSING_ON_HAND * p.UNIT_COST,
        COALESCE(t.UNITS_RECEIVED, 0),
        COALESCE(t.UNITS_SOLD, 0),
        COALESCE(t.UNITS_ADJUSTED, 0),
        COALESCE(l7.AVG_DAILY_UNITS_SOLD, 0),
        c.CLOSING_ON_HAND < 3 * COALESCE(l7.AVG_DAILY_UNITS_SOLD, 0)   -- < 3 days of cover
    FROM closing c
    LEFT JOIN today t        ON t.STORE_ID = c.STORE_ID AND t.PRODUCT_ID = c.PRODUCT_ID
    LEFT JOIN last_7_days l7 ON l7.STORE_ID = c.STORE_ID AND l7.PRODUCT_ID = c.PRODUCT_ID
    LEFT JOIN {{DATABASE}}.ANALYTICS.DIM_STORE st ON st.STORE_ID = c.STORE_ID
    LEFT JOIN {{DATABASE}}.ANALYTICS.DIM_PRODUCT p
           ON p.PRODUCT_ID = c.PRODUCT_ID
          AND p.EFFECTIVE_FROM_UTC < :end_of_day_utc AND p.EFFECTIVE_TO_UTC >= :end_of_day_utc;
    rows_written := SQLROWCOUNT;

    COMMIT;
    RETURN 'inventory snapshot ' || d || ': ' || rows_written || ' rows';
EXCEPTION
    WHEN OTHER THEN
        ROLLBACK;
        RAISE;
END;
$$;

-- Backfill helper: CALL ANALYTICS.SP_BACKFILL_INVENTORY_SNAPSHOTS('2026-09-01', '2026-09-29');
CREATE OR REPLACE PROCEDURE {{DATABASE}}.ANALYTICS.SP_BACKFILL_INVENTORY_SNAPSHOTS(P_FROM DATE, P_TO DATE)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    d DATE;
    days INTEGER DEFAULT 0;
BEGIN
    d := P_FROM;
    WHILE (d <= P_TO) DO
        CALL {{DATABASE}}.ANALYTICS.SP_BUILD_INVENTORY_SNAPSHOT(:d);
        d := DATEADD(DAY, 1, d);
        days := days + 1;
    END WHILE;
    RETURN 'snapshots built for ' || days || ' days';
END;
$$;
