-- =============================================================================
-- Analyst-facing views on the star schema. Views cost nothing until queried.
-- =============================================================================

-- Sales lines with "as-was" dimension attributes (the version valid at sale time).
CREATE OR REPLACE VIEW {{DATABASE}}.ANALYTICS.VW_SALES COPY GRANTS
COMMENT = 'FACT_SALES joined to its dimensions - product/customer attributes as they were when sold.'
AS
SELECT
    f.TRANSACTION_ID, f.LINE_NUMBER, f.EVENT_TS_UTC, f.EVENT_TS_LOCAL, f.LOCAL_HOUR,
    d.FULL_DATE AS BUSINESS_DATE, d.YEAR_MONTH, d.ISO_WEEK, d.DAY_NAME, d.IS_WEEKEND, d.IS_PUBLIC_HOLIDAY,
    s.STORE_ID, s.STORE_NAME, s.CITY AS STORE_CITY, s.STATE AS STORE_STATE, s.REGION, s.STORE_FORMAT, s.SIZE_SQM,
    p.PRODUCT_ID, p.PRODUCT_NAME, p.BRAND, p.CATEGORY, p.SUBCATEGORY, p.IS_INFERRED AS PRODUCT_IS_INFERRED,
    c.CUSTOMER_ID, c.LOYALTY_TIER, c.AGE_BAND,
    f.PAYMENT_METHOD, f.QUANTITY, f.UNIT_PRICE, f.GROSS_AMOUNT, f.DISCOUNT_AMOUNT, f.NET_AMOUNT,
    f.COST_AMOUNT, f.NET_AMOUNT - f.COST_AMOUNT AS GROSS_MARGIN
FROM {{DATABASE}}.ANALYTICS.FACT_SALES f
JOIN {{DATABASE}}.ANALYTICS.DIM_DATE d     ON d.DATE_KEY = f.DATE_KEY
JOIN {{DATABASE}}.ANALYTICS.DIM_STORE s    ON s.STORE_KEY = f.STORE_KEY
JOIN {{DATABASE}}.ANALYTICS.DIM_PRODUCT p  ON p.PRODUCT_KEY = f.PRODUCT_KEY
JOIN {{DATABASE}}.ANALYTICS.DIM_CUSTOMER c ON c.CUSTOMER_KEY = f.CUSTOMER_KEY;

-- "As-is" view of products: current attributes only (restates history under today's category).
CREATE OR REPLACE VIEW {{DATABASE}}.ANALYTICS.VW_DIM_PRODUCT_CURRENT COPY GRANTS AS
SELECT * FROM {{DATABASE}}.ANALYTICS.DIM_PRODUCT WHERE IS_CURRENT;

CREATE OR REPLACE VIEW {{DATABASE}}.ANALYTICS.VW_DIM_CUSTOMER_CURRENT COPY GRANTS AS
SELECT * FROM {{DATABASE}}.ANALYTICS.DIM_CUSTOMER WHERE IS_CURRENT;

-- Latest inventory position per store x product.
CREATE OR REPLACE VIEW {{DATABASE}}.ANALYTICS.VW_INVENTORY_POSITION COPY GRANTS AS
SELECT sn.*, s.STORE_NAME, s.REGION, p.PRODUCT_NAME, p.CATEGORY, p.SUBCATEGORY
FROM {{DATABASE}}.ANALYTICS.FACT_INVENTORY_SNAPSHOT sn
JOIN {{DATABASE}}.ANALYTICS.DIM_STORE s   ON s.STORE_KEY = sn.STORE_KEY
JOIN {{DATABASE}}.ANALYTICS.DIM_PRODUCT p ON p.PRODUCT_KEY = sn.PRODUCT_KEY
WHERE sn.DATE_KEY = (SELECT MAX(DATE_KEY) FROM {{DATABASE}}.ANALYTICS.FACT_INVENTORY_SNAPSHOT);

-- Pipeline freshness: how far behind real time each layer is (used by rule SF-007).
CREATE OR REPLACE VIEW {{DATABASE}}.OPS.VW_PIPELINE_FRESHNESS COPY GRANTS AS
SELECT 'RAW.POS_TRANSACTIONS' AS LAYER, MAX(EVENT_TIMESTAMP) AS MAX_EVENT_TS_UTC, MAX(_LOADED_AT) AS LAST_LOADED_AT
FROM {{DATABASE}}.RAW.POS_TRANSACTIONS
UNION ALL
SELECT 'STAGING.STG_POS_TRANSACTION_LINES', MAX(EVENT_TS_UTC), MAX(_STAGED_AT)
FROM {{DATABASE}}.STAGING.STG_POS_TRANSACTION_LINES
UNION ALL
SELECT 'ANALYTICS.FACT_SALES', MAX(EVENT_TS_UTC), MAX(_LOADED_AT)
FROM {{DATABASE}}.ANALYTICS.FACT_SALES;
