-- =============================================================================
-- Object privileges (least privilege, ADR-005). Repeatable: re-applied whenever it changes,
-- and it runs last so it also covers objects created by earlier scripts.
--
--   RETAIL_ADMIN        owns everything (runs migrations)
--   RETAIL_LOADER       PUT to the stage, COPY into RAW - nothing else
--   RETAIL_TRANSFORMER  owns the tasks; may only CALL the owner's-rights procedures, so it
--                       cannot run arbitrary DML itself
--   RETAIL_ANALYST      SELECT on ANALYTICS only
-- =============================================================================

-- ----------------------------------------------------------------------------- loader
GRANT USAGE ON SCHEMA {{DATABASE}}.RAW TO ROLE RETAIL_LOADER;
GRANT READ, WRITE ON STAGE {{DATABASE}}.RAW.LANDING_STAGE TO ROLE RETAIL_LOADER;
GRANT USAGE ON FILE FORMAT {{DATABASE}}.RAW.FF_PARQUET TO ROLE RETAIL_LOADER;
GRANT USAGE ON FILE FORMAT {{DATABASE}}.RAW.FF_STORES_CSV TO ROLE RETAIL_LOADER;
GRANT INSERT, SELECT ON TABLE {{DATABASE}}.RAW.POS_TRANSACTIONS    TO ROLE RETAIL_LOADER;
GRANT INSERT, SELECT ON TABLE {{DATABASE}}.RAW.INVENTORY_MOVEMENTS TO ROLE RETAIL_LOADER;
GRANT INSERT, SELECT ON TABLE {{DATABASE}}.RAW.CUSTOMER_EVENTS     TO ROLE RETAIL_LOADER;
GRANT INSERT, SELECT ON TABLE {{DATABASE}}.RAW.PRODUCT_EVENTS      TO ROLE RETAIL_LOADER;
GRANT INSERT, SELECT ON TABLE {{DATABASE}}.RAW.DEAD_LETTERS        TO ROLE RETAIL_LOADER;
GRANT INSERT, SELECT ON TABLE {{DATABASE}}.RAW.INGEST_BATCH_AUDIT  TO ROLE RETAIL_LOADER;
GRANT INSERT, SELECT ON TABLE {{DATABASE}}.RAW.STORE_REFERENCE     TO ROLE RETAIL_LOADER;

-- ----------------------------------------------------------------------------- transformer
GRANT USAGE ON SCHEMA {{DATABASE}}.RAW       TO ROLE RETAIL_TRANSFORMER;
GRANT USAGE ON SCHEMA {{DATABASE}}.STAGING   TO ROLE RETAIL_TRANSFORMER;
GRANT USAGE ON SCHEMA {{DATABASE}}.ANALYTICS TO ROLE RETAIL_TRANSFORMER;
GRANT USAGE ON SCHEMA {{DATABASE}}.OPS       TO ROLE RETAIL_TRANSFORMER;
-- Needed to evaluate the root task's WHEN SYSTEM$STREAM_HAS_DATA(...) conditions.
GRANT SELECT ON ALL STREAMS IN SCHEMA {{DATABASE}}.RAW     TO ROLE RETAIL_TRANSFORMER;
GRANT SELECT ON ALL STREAMS IN SCHEMA {{DATABASE}}.STAGING TO ROLE RETAIL_TRANSFORMER;
GRANT SELECT ON ALL TABLES  IN SCHEMA {{DATABASE}}.RAW     TO ROLE RETAIL_TRANSFORMER;
GRANT SELECT ON ALL TABLES  IN SCHEMA {{DATABASE}}.STAGING TO ROLE RETAIL_TRANSFORMER;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA {{DATABASE}}.STAGING   TO ROLE RETAIL_TRANSFORMER;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA {{DATABASE}}.ANALYTICS TO ROLE RETAIL_TRANSFORMER;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA {{DATABASE}}.OPS       TO ROLE RETAIL_TRANSFORMER;

-- Tasks run with their OWNER's privileges. Hand them to the transformer (tasks are suspended
-- after CREATE OR REPLACE, which ownership transfer requires).
GRANT OWNERSHIP ON TASK {{DATABASE}}.OPS.TASK_PIPELINE_ROOT      TO ROLE RETAIL_TRANSFORMER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON TASK {{DATABASE}}.OPS.TASK_DIMENSIONS         TO ROLE RETAIL_TRANSFORMER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON TASK {{DATABASE}}.OPS.TASK_FACTS              TO ROLE RETAIL_TRANSFORMER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON TASK {{DATABASE}}.OPS.TASK_DQ_CHECKS          TO ROLE RETAIL_TRANSFORMER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON TASK {{DATABASE}}.OPS.TASK_INVENTORY_SNAPSHOT TO ROLE RETAIL_TRANSFORMER COPY CURRENT GRANTS;

-- ----------------------------------------------------------------------------- analyst
GRANT USAGE ON SCHEMA {{DATABASE}}.ANALYTICS TO ROLE RETAIL_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA {{DATABASE}}.ANALYTICS    TO ROLE RETAIL_ANALYST;
GRANT SELECT ON ALL VIEWS  IN SCHEMA {{DATABASE}}.ANALYTICS    TO ROLE RETAIL_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA {{DATABASE}}.ANALYTICS TO ROLE RETAIL_ANALYST;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA {{DATABASE}}.ANALYTICS TO ROLE RETAIL_ANALYST;
GRANT USAGE ON ALL FUNCTIONS IN SCHEMA {{DATABASE}}.ANALYTICS  TO ROLE RETAIL_ANALYST;
-- Analysts may see data-quality status and freshness (read-only), but no pipeline internals.
GRANT USAGE ON SCHEMA {{DATABASE}}.OPS TO ROLE RETAIL_ANALYST;
GRANT SELECT ON VIEW {{DATABASE}}.OPS.VW_DQ_LATEST TO ROLE RETAIL_ANALYST;
GRANT SELECT ON VIEW {{DATABASE}}.OPS.VW_PIPELINE_FRESHNESS TO ROLE RETAIL_ANALYST;
GRANT SELECT ON TABLE {{DATABASE}}.OPS.DQ_RESULTS TO ROLE RETAIL_ANALYST;
